# test1:
#  script:
#    - echo $CI_PIPELINE_IID
#test2:
#  script:
#    - echo $CI_PIPELINE_IID
test1:
  script:
    - echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget massa felis. Aliquam quis aliquet est. Morbi aliquet varius ligula, quis iaculis urna interdum at. Aliquam nec nibh neque. Curabitur ac nibh velit. Nam quis sem purus. Sed sed dui interdum, tristique magna porttitor, pellentesque neque. Nunc accumsan leo vitae ligula tincidunt pharetra. Integer scelerisque placerat eros sit amet ullamcorper. Etiam sit amet leo vestibulum, iaculis nulla a, egestas dolor. Cras quis felis eu erat placerat dapibus. Maecenas quis lorem id tortor elementum commodo. Suspendisse in purus a purus blandit aliquet. Donec interdum scelerisque convallis. Mauris fringilla, felis eu semper finibus, augue mauris sollicitudin nisl, et mattis magna urna vel orci. Vestibulum lacus elit, ullamcorper tempus mi ut, pellentesque pharetra lorem."